# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06-callbacks.ipynb (unless otherwise specified).

__all__ = ['StackVolumesCallback']

# Cell
# default_exp callback

from fastai.basics import *
from fastai.vision.all import *
from fastai.callback.all import *

# Cell

from .basics import *
from .augment import *
from .data import *
from .models import *

# Cell
class StackVolumesCallback(Callback):
    def before_batch(self):
        self.learn.xb = (torch.cat(self.learn.xb, dim=1), )