name: fastai
channels:
  - pytorch
  - fastai
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - pip=20.2.4
  - nb_conda_kernels=2.3.1
  - fastai=2.1.10
  - fastcore=1.3.16
  - libuv=1.40.0
  - nbdev=1.1.5
  - scikit-image=0.17.2
  - pydicom=2.0.0
  - pytorch=1.7.0
  - rpy2=2.9.4
  - torchvision=0.8.1
  - jupyterlab=3.0.5
  - pip:
    - kornia==0.4.1
    - simpleitk==2.0.2
    - opencv-python==4.5.1.48
