# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/98_widgets.ipynb (unless otherwise specified).

__all__ = ['is_lab']

# Cell
# default_exp widgets.viewer
from ..basics import *
from ..data import *
from ..augment import *
from fastai.basics import *

# Cell
from ipywidgets import interactive, widgets
from IPython.display import display
import matplotlib.pyplot as plt
from itertools import chain, islice

# Cell
from warnings import warn
def is_lab():
        import re
        import psutil

        return any(re.search('jupyter-lab', x)
                   for x in psutil.Process().parent().cmdline())
if is_lab():
    warn('The faimed3d image viewer requires Jupyter Notebook to work properly')