# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05a_models.modules.ipynb (unless otherwise specified).

__all__ = ['Sequential_']

# Cell
# export
from torch import nn, Tensor
import torch.nn.functional as F
from warnings import warn

# Cell
class Sequential_(nn.Sequential):
    "Similar to nn.Sequential, but copies input to cuda"
    def forward(self, input):
        for module in self:
            input = module(input.cuda())
        return input