repository: kbressem/faimed3d
output: web
topnav_title: faimed3d
site_title: faimed3d
description: A addon to fastai for volumetric medical data
google_search: a5fee9aeb028b0999
use_math: true
google_analytics:
twitter_username: k_bressem

host: 127.0.0.1
# the preview server used. Leave as is.
port: 4000
# the port where the preview is rendered.

exclude:
  - .idea/
  - .gitignore
  - vendor

exclude: [vendor]

default_badges:
  colab: false

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

sidebars: [home_sidebar]
baseurl: /
plugins:
    - jekyll-remote-theme

remote_theme: fastai/nbdev-jekyll-theme
